<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Http;

/**
 * HTTP Methods Enumeration
 */
class HttpMethod
{
    public const GET = "Get";
    public const POST = "Post";
    public const PUT = "Put";
    public const PATCH = "Patch";
    public const DELETE = "Delete";
    public const HEAD = "Head";
}
