<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use stdClass;

class Footer implements \JsonSerializable
{
    /**
     * @var string
     */
    private $text;

    /**
     * @param string $text
     */
    public function __construct(string $text)
    {
        $this->text = $text;
    }

    /**
     * Returns Text.
     * The footer content. Emojis and markdown are supported. Links are supported.
     */
    public function getText(): string
    {
        return $this->text;
    }

    /**
     * Sets Text.
     * The footer content. Emojis and markdown are supported. Links are supported.
     *
     * @required
     * @maps text
     */
    public function setText(string $text): void
    {
        $this->text = $text;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['text'] = $this->text;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
