<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use stdClass;

class Header implements \JsonSerializable
{
    /**
     * @var string
     */
    private $type;

    /**
     * @var string|null
     */
    private $text;

    /**
     * @var Video|null
     */
    private $video;

    /**
     * @var Image|null
     */
    private $image;

    /**
     * @var Document|null
     */
    private $document;

    /**
     * @param string $type
     */
    public function __construct(string $type)
    {
        $this->type = $type;
    }

    /**
     * Returns Type.
     * The header type you would like to use.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The header type you would like to use.
     *
     * @required
     * @maps type
     * @factory \WhatsAppCloudAPILib\Models\HeaderTypeEnum::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Text.
     * Required if type is set to text. Text for the header. Formatting allows emojis, but not markdown.
     */
    public function getText(): ?string
    {
        return $this->text;
    }

    /**
     * Sets Text.
     * Required if type is set to text. Text for the header. Formatting allows emojis, but not markdown.
     *
     * @maps text
     */
    public function setText(?string $text): void
    {
        $this->text = $text;
    }

    /**
     * Returns Video.
     * Required if type is set to video. Contains the media object for this video.
     */
    public function getVideo(): ?Video
    {
        return $this->video;
    }

    /**
     * Sets Video.
     * Required if type is set to video. Contains the media object for this video.
     *
     * @maps video
     */
    public function setVideo(?Video $video): void
    {
        $this->video = $video;
    }

    /**
     * Returns Image.
     * Required if type is set to image. Contains the media object for this image.
     */
    public function getImage(): ?Image
    {
        return $this->image;
    }

    /**
     * Sets Image.
     * Required if type is set to image. Contains the media object for this image.
     *
     * @maps image
     */
    public function setImage(?Image $image): void
    {
        $this->image = $image;
    }

    /**
     * Returns Document.
     * Required if type is set to document. Contains the media object for this document.
     */
    public function getDocument(): ?Document
    {
        return $this->document;
    }

    /**
     * Sets Document.
     * Required if type is set to document. Contains the media object for this document.
     *
     * @maps document
     */
    public function setDocument(?Document $document): void
    {
        $this->document = $document;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['type']         = HeaderTypeEnum::checkValue($this->type);
        if (isset($this->text)) {
            $json['text']     = $this->text;
        }
        if (isset($this->video)) {
            $json['video']    = $this->video;
        }
        if (isset($this->image)) {
            $json['image']    = $this->image;
        }
        if (isset($this->document)) {
            $json['document'] = $this->document;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
