<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use stdClass;

class Interactive implements \JsonSerializable
{
    /**
     * @var Action
     */
    private $action;

    /**
     * @var Body
     */
    private $body;

    /**
     * @var Footer|null
     */
    private $footer;

    /**
     * @var Header|null
     */
    private $header;

    /**
     * @var string
     */
    private $type;

    /**
     * @param Action $action
     * @param Body $body
     * @param string $type
     */
    public function __construct(Action $action, Body $body, string $type)
    {
        $this->action = $action;
        $this->body = $body;
        $this->type = $type;
    }

    /**
     * Returns Action.
     * Action you want the user to perform after reading the message.
     */
    public function getAction(): Action
    {
        return $this->action;
    }

    /**
     * Sets Action.
     * Action you want the user to perform after reading the message.
     *
     * @required
     * @maps action
     */
    public function setAction(Action $action): void
    {
        $this->action = $action;
    }

    /**
     * Returns Body.
     * The body of the message. Emojis and markdown are supported.
     */
    public function getBody(): Body
    {
        return $this->body;
    }

    /**
     * Sets Body.
     * The body of the message. Emojis and markdown are supported.
     *
     * @required
     * @maps body
     */
    public function setBody(Body $body): void
    {
        $this->body = $body;
    }

    /**
     * Returns Footer.
     * The footer of the message. Emojis and markdown are supported.
     */
    public function getFooter(): ?Footer
    {
        return $this->footer;
    }

    /**
     * Sets Footer.
     * The footer of the message. Emojis and markdown are supported.
     *
     * @maps footer
     */
    public function setFooter(?Footer $footer): void
    {
        $this->footer = $footer;
    }

    /**
     * Returns Header.
     * Header content displayed on top of a message.
     */
    public function getHeader(): ?Header
    {
        return $this->header;
    }

    /**
     * Sets Header.
     * Header content displayed on top of a message.
     *
     * @maps header
     */
    public function setHeader(?Header $header): void
    {
        $this->header = $header;
    }

    /**
     * Returns Type.
     * The type of interactive message you want to send.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of interactive message you want to send.
     *
     * @required
     * @maps type
     * @factory \WhatsAppCloudAPILib\Models\InteractiveTypeEnum::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['action']     = $this->action;
        $json['body']       = $this->body;
        if (isset($this->footer)) {
            $json['footer'] = $this->footer;
        }
        if (isset($this->header)) {
            $json['header'] = $this->header;
        }
        $json['type']       = InteractiveTypeEnum::checkValue($this->type);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
