<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use stdClass;

class Name implements \JsonSerializable
{
    /**
     * @var string
     */
    private $formattedName;

    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var string|null
     */
    private $lastName;

    /**
     * @var string|null
     */
    private $middleName;

    /**
     * @var string|null
     */
    private $suffix;

    /**
     * @var string|null
     */
    private $prefix;

    /**
     * @param string $formattedName
     */
    public function __construct(string $formattedName)
    {
        $this->formattedName = $formattedName;
    }

    /**
     * Returns Formatted Name.
     * Full name, as it normally appears.
     */
    public function getFormattedName(): string
    {
        return $this->formattedName;
    }

    /**
     * Sets Formatted Name.
     * Full name, as it normally appears.
     *
     * @required
     * @maps formatted_name
     */
    public function setFormattedName(string $formattedName): void
    {
        $this->formattedName = $formattedName;
    }

    /**
     * Returns First Name.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     *
     * @maps first_name
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Last Name.
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     *
     * @maps last_name
     */
    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Middle Name.
     */
    public function getMiddleName(): ?string
    {
        return $this->middleName;
    }

    /**
     * Sets Middle Name.
     *
     * @maps middle_name
     */
    public function setMiddleName(?string $middleName): void
    {
        $this->middleName = $middleName;
    }

    /**
     * Returns Suffix.
     */
    public function getSuffix(): ?string
    {
        return $this->suffix;
    }

    /**
     * Sets Suffix.
     *
     * @maps suffix
     */
    public function setSuffix(?string $suffix): void
    {
        $this->suffix = $suffix;
    }

    /**
     * Returns Prefix.
     */
    public function getPrefix(): ?string
    {
        return $this->prefix;
    }

    /**
     * Sets Prefix.
     *
     * @maps prefix
     */
    public function setPrefix(?string $prefix): void
    {
        $this->prefix = $prefix;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['formatted_name']  = $this->formattedName;
        if (isset($this->firstName)) {
            $json['first_name']  = $this->firstName;
        }
        if (isset($this->lastName)) {
            $json['last_name']   = $this->lastName;
        }
        if (isset($this->middleName)) {
            $json['middle_name'] = $this->middleName;
        }
        if (isset($this->suffix)) {
            $json['suffix']      = $this->suffix;
        }
        if (isset($this->prefix)) {
            $json['prefix']      = $this->prefix;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
