<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use stdClass;

class Org implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $company;

    /**
     * @var string|null
     */
    private $department;

    /**
     * @var string|null
     */
    private $title;

    /**
     * Returns Company.
     * Name of the contact's company.
     */
    public function getCompany(): ?string
    {
        return $this->company;
    }

    /**
     * Sets Company.
     * Name of the contact's company.
     *
     * @maps company
     */
    public function setCompany(?string $company): void
    {
        $this->company = $company;
    }

    /**
     * Returns Department.
     * Name of the contact's department.
     */
    public function getDepartment(): ?string
    {
        return $this->department;
    }

    /**
     * Sets Department.
     * Name of the contact's department.
     *
     * @maps department
     */
    public function setDepartment(?string $department): void
    {
        $this->department = $department;
    }

    /**
     * Returns Title.
     * Contact's business title.
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     * Contact's business title.
     *
     * @maps title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->company)) {
            $json['company']    = $this->company;
        }
        if (isset($this->department)) {
            $json['department'] = $this->department;
        }
        if (isset($this->title)) {
            $json['title']      = $this->title;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
