<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use stdClass;

class ResponseContact implements \JsonSerializable
{
    /**
     * @var string
     */
    private $input;

    /**
     * @var string
     */
    private $waId;

    /**
     * @param string $input
     * @param string $waId
     */
    public function __construct(string $input, string $waId)
    {
        $this->input = $input;
        $this->waId = $waId;
    }

    /**
     * Returns Input.
     */
    public function getInput(): string
    {
        return $this->input;
    }

    /**
     * Sets Input.
     *
     * @required
     * @maps input
     */
    public function setInput(string $input): void
    {
        $this->input = $input;
    }

    /**
     * Returns Wa Id.
     */
    public function getWaId(): string
    {
        return $this->waId;
    }

    /**
     * Sets Wa Id.
     *
     * @required
     * @maps wa_id
     */
    public function setWaId(string $waId): void
    {
        $this->waId = $waId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['input'] = $this->input;
        $json['wa_id'] = $this->waId;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
