<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use stdClass;

class Section implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $title;

    /**
     * @var Row[]|null
     */
    private $rows;

    /**
     * Returns Title.
     * Required if the message has more than one section. Title of the section.
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     * Required if the message has more than one section. Title of the section.
     *
     * @maps title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Rows.
     * Required for List Messages. Contains a list of rows. You can have a total of 10 rows across your
     * sections. Each row must have a title (Maximum length: 24 characters) and an ID (Maximum length: 200
     * characters). You can add a description (Maximum length: 72 characters), but it is optional.
     *
     * @return Row[]|null
     */
    public function getRows(): ?array
    {
        return $this->rows;
    }

    /**
     * Sets Rows.
     * Required for List Messages. Contains a list of rows. You can have a total of 10 rows across your
     * sections. Each row must have a title (Maximum length: 24 characters) and an ID (Maximum length: 200
     * characters). You can add a description (Maximum length: 72 characters), but it is optional.
     *
     * @maps rows
     *
     * @param Row[]|null $rows
     */
    public function setRows(?array $rows): void
    {
        $this->rows = $rows;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->title)) {
            $json['title'] = $this->title;
        }
        if (isset($this->rows)) {
            $json['rows']  = $this->rows;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
