<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use stdClass;

class SendMessageResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $messagingProduct;

    /**
     * @var ResponseContact[]
     */
    private $contacts;

    /**
     * @var ResponseMessage[]
     */
    private $messages;

    /**
     * @param string $messagingProduct
     * @param ResponseContact[] $contacts
     * @param ResponseMessage[] $messages
     */
    public function __construct(string $messagingProduct, array $contacts, array $messages)
    {
        $this->messagingProduct = $messagingProduct;
        $this->contacts = $contacts;
        $this->messages = $messages;
    }

    /**
     * Returns Messaging Product.
     */
    public function getMessagingProduct(): string
    {
        return $this->messagingProduct;
    }

    /**
     * Sets Messaging Product.
     *
     * @required
     * @maps messaging_product
     */
    public function setMessagingProduct(string $messagingProduct): void
    {
        $this->messagingProduct = $messagingProduct;
    }

    /**
     * Returns Contacts.
     *
     * @return ResponseContact[]
     */
    public function getContacts(): array
    {
        return $this->contacts;
    }

    /**
     * Sets Contacts.
     *
     * @required
     * @maps contacts
     *
     * @param ResponseContact[] $contacts
     */
    public function setContacts(array $contacts): void
    {
        $this->contacts = $contacts;
    }

    /**
     * Returns Messages.
     *
     * @return ResponseMessage[]
     */
    public function getMessages(): array
    {
        return $this->messages;
    }

    /**
     * Sets Messages.
     *
     * @required
     * @maps messages
     *
     * @param ResponseMessage[] $messages
     */
    public function setMessages(array $messages): void
    {
        $this->messages = $messages;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['messaging_product'] = $this->messagingProduct;
        $json['contacts']          = $this->contacts;
        $json['messages']          = $this->messages;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
