<?php

declare(strict_types=1);

/*
 * WhatsAppCloudAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace WhatsAppCloudAPILib\Models;

use Exception;
use stdClass;
use WhatsAppCloudAPILib\ApiHelper;

class VerticalEnum
{
    public const UNDEFINED = 'UNDEFINED';

    public const OTHER = 'OTHER';

    public const AUTO = 'AUTO';

    public const BEAUTY = 'BEAUTY';

    public const APPAREL = 'APPAREL';

    public const EDU = 'EDU';

    public const ENTERTAIN = 'ENTERTAIN';

    public const EVENT_PLAN = 'EVENT_PLAN';

    public const FINANCE = 'FINANCE';

    public const GROCERY = 'GROCERY';

    public const GOVT = 'GOVT';

    public const HOTEL = 'HOTEL';

    public const HEALTH = 'HEALTH';

    public const NONPROFIT = 'NONPROFIT';

    public const PROF_SERVICES = 'PROF_SERVICES';

    public const RETAIL = 'RETAIL';

    public const TRAVEL = 'TRAVEL';

    public const RESTAURANT = 'RESTAURANT';

    public const NOT_A_BIZ = 'NOT_A_BIZ';

    private const _ALL_VALUES = [
        self::UNDEFINED,
        self::OTHER,
        self::AUTO,
        self::BEAUTY,
        self::APPAREL,
        self::EDU,
        self::ENTERTAIN,
        self::EVENT_PLAN,
        self::FINANCE,
        self::GROCERY,
        self::GOVT,
        self::HOTEL,
        self::HEALTH,
        self::NONPROFIT,
        self::PROF_SERVICES,
        self::RETAIL,
        self::TRAVEL,
        self::RESTAURANT,
        self::NOT_A_BIZ,
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        ApiHelper::checkValueInEnum($value, self::class, self::_ALL_VALUES);
        return $value;
    }
}
